### ISSUE TITLE
How can we cache https?

### ISSUE THREAD

**Issue by tcagkansokmen** [aryehraber/statamic-fetch#18] opened 2018-09-18 07:37 UTC
Hi

Thanks for that addon. I'm confused about caching requests.
How can I cache a request for several time?

**Comment by makkinga** [comment] 2018-11-22 12:01
I'll dive into this in a few days. I need some caching myself

**Comment by makkinga** [comment] 2018-11-27 15:58
@tcagkansokmen I've written the code today, as soon as @aryehraber has merged (of declined) the other open PR's I'll make a PR for this

**Comment by grideca** [comment] 2019-10-29 15:20
Hi @makkinga,
Awesome that you already have the code!
I would be interested in this feature. Could you possibly create a PR now?
thanks :)

**Comment by bendeca** [comment] 2019-10-29 15:21
Hi @makkinga ,
Awesome that you already have the code!
I would be interested in this feature. Could you possibly create a PR now?
thanks :)

**Comment by makkinga** [comment] 2019-10-31 09:48
Hi @bendeca,

It has been a while since i've worked on this and I lost access to the code I mentioned above when I started working for another company a while ago.
Luckily it wasn't too hard to reproduce. I'll have a look into it today. I expect to make a PR before the end of the day.

**Closed** 2019-11-08 16:42 UTC
Labels: feature request
