### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by mrkaluzny** [aryehraber/statamic-fetch#7] opened 2017-10-02 13:44 UTC
Hey! 

I got a problem with `array_merge` function. Any idea what might have caused that? I would could really use some help with this.

**Comment by aryehraber** [comment] 2017-10-02 14:58
Hi @mrkaluzny!

Can you add some more details about the issue/project?

- Statamic version
- Full error stack trace
- Example of the data you're trying to access

I should mention that this Addon hasn't been tested with the latest version(s) of Statamic. There were some changes to the way Addons work in 2.6+ so this _might_ be the cause... Haven't had the time to thoroughly test yet.

**Comment by mrkaluzny** [comment] 2017-10-02 15:48
Hi @aryehraber, thanks for the reply.

Statamic version: 2.6.9
Full error stack trace: [terzakis-error.pdf](https://github.com/aryehraber/statamic-fetch/files/1349452/terzakis-error.pdf)

I'm trying to access blog collection but the error is basically the same on every request (Page or Collection). I haven't made any changes to initial settings or added any methods. So it's probably statamic version update.

**Comment by aryehraber** [comment] 2017-10-02 15:54
Thanks for the details @mrkaluzny, I'll try and update my local dev environment for this Addon to the latest Statamic version soon and see if I run into the same issue.

Can't give an exact timeframe though due to work commitments. If you're up for getting your hands dirty, feel free to dive in and submit a Pull Request if you find a solution.

**Comment by mrkaluzny** [comment] 2017-10-02 15:55
@aryehraber  I'll try to find a solution to that or just build a custom addon/api endpoint for blog posts. I'll keep you posted

**Comment by aryehraber** [comment] 2017-10-02 15:57
@mrkaluzny Ok, sounds good! A temp. solution would be to downgrade Statamic to v2.5.11 which I believe is where I tested it last. Unless you're already using 2.6+ features...

**Comment by aryehraber** [comment] 2017-10-04 09:49
Hey @mrkaluzny, I just updated my local dev environment for Fetch to the latest Statamic (v2.6.9) and everything seems to be working fine.

Would you mind sharing some example entries from your Blog collection?

**Comment by aryehraber** [comment] 2018-01-08 09:40
Closing this issue as I am still not able to reproduce.

Feel free to re-open if you're still facing this problem and can supply more details (example data, etc.)

**Comment by aryehraber** [comment] 2018-01-08 11:19
After some more digging, I was finally about to reproduce. Fix coming up!

**Comment by mrkaluzny** [comment] 2018-01-08 11:28
Perfect 👍 I ended up creating an Addon on this one :)

**Closed** 2018-01-08 12:49 UTC
Labels: bug

**Comment by aryehraber** [comment] 2018-01-08 12:51
This issue should be fixed now.

I you ever come back to using this Addon instead of your own, let me know if you have any further issues!
