### ISSUE TITLE
Cache request

### ISSUE THREAD

**Issue by sweebee** [aryehraber/statamic-fetch#42] opened 2019-01-08 08:55 UTC
Is it possible to cache a request? I have to return a collection with 600 items, but it takes around 15 seconds to load.

**Comment by aryehraber** [comment] 2019-01-09 11:21
Hi @sweebee, no caching layer yet I'm afraid. It's on the roadmap but without a timeline for it atm.

Closing as it's a dupe of https://github.com/aryehraber/statamic-fetch/issues/18

**Closed by aryehraber** 2019-01-09 11:21 UTC
